"""Alembic environment for MagicBot.

Intentionally standalone — does NOT import the Flask app. Loads the DB URL
from the environment (matching the lookup app.py uses) so `alembic upgrade`
commands are fast and don't run init_db(), seeding, or model registration.

Migration files use SQLAlchemy + Alembic primitives directly; they do not
import models.py so they're stable against future model edits.
"""
import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)


# Match the resolution order in app.py: SQLALCHEMY_DATABASE_URI env var,
# fallback to local SQLite (instance/magic_bot.db is Flask-SQLAlchemy's
# default location when using sqlite:///magic_bot.db).
_db_uri = os.environ.get('SQLALCHEMY_DATABASE_URI', '')
if not _db_uri:
    _instance_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'instance', 'magic_bot.db',
    )
    _db_uri = f"sqlite:///{_instance_path}"
config.set_main_option('sqlalchemy.url', _db_uri.replace('%', '%%'))


# We don't pass target_metadata because migrations are hand-written, not
# autogenerated. If you ever need autogenerate, import db.metadata from
# extensions inside a Flask app context here.
target_metadata = None


def run_migrations_offline():
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,  # SQLite-friendly: emits batch_alter_table
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # SQLite needs this for ALTER COLUMN / DROP COLUMN
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
